name: (5.x) Generate index templates

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "ecs/**/*.json"
      - "ecs/**/*.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-ecs-generator:
    if: github.repository == 'wazuh/wazuh-indexer-plugins'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
    env:
      output_folder: /tmp/ecs-templates

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: branch-name

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Generate PR to wazuh-indexer-plugins
        id: generate-pr
        env:
          GITHUB_TOKEN: ${{ secrets.INDEXER_BOT_TOKEN }}
          COMMITER_EMAIL: ${{ secrets.INDEXER_BOT_EMAIL }}
          COMMITTER_USERNAME: "Wazuh Indexer Bot"
          SSH_PRIVATE_KEY: ${{ secrets.INDEXER_BOT_PRIVATE_SSH_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.INDEXER_BOT_PUBLIC_SSH_KEY }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          bash ecs/scripts/generate_and_push_templates.sh \
            -b ${{ steps.branch-name.outputs.branch }} \
            -o ${{ env.output_folder }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecs-templates
          path: ${{ env.output_folder }}
